### ISSUE TITLE
Website hacked?

### ISSUE THREAD

**Issue by vic-t** [mantisbt-plugins/codev#3]
In the unlikely case you are not aware yet, your website codevtt.org is no longer accessible, i.e. redirects to some non-related content.

**Comment by Nikerabbit** [comment]
Seems to be known per 80b23f45c975878d182218a8ab3a981e18e22b58. Are there outdated links somewhere pointing to the old address?

**Comment by lbayle** [comment]
Hi,
in deed, the codevtt.org website is no more maintained, GitHub is now the official website.
There may be some remaining references to this URL, if you find any, please report so that I can fix.

the CodevTT app is still maintained and I will continue to publish one release/year.

Best regards

**Comment by vic-t** [comment]
@lbayle 

There are multiple references to the URL on this Github repository alone. 

![image](https://user-images.githubusercontent.com/13408858/162702979-3a154a20-3aa3-4331-9c70-2eae572c905d.png)

![image](https://user-images.githubusercontent.com/13408858/162702995-91f313b8-9fd2-4b79-9963-338fe15c5c82.png)

The two links in the screenshot above also point to codevtt.org. 

Do you have another place where you store screenshots and documentation for Codev? If not, maybe the repository wiki would be a good place as it's also free and other people could contribute.

**Comment by lbayle** [comment]
Hi, I no longer maintain the codevtt.org website.
after 10 years with no donations for codevtt, I decided not to spend any
more money for the website.
The official website is now github.
Nevertheless, codevtt is still maintained and I will continue to publish
one release/year as long as my company and I  will use it.

Best regards

Le mar. 5 avr. 2022 à 07:48, Niklas Laxström ***@***.***> a
écrit :
